### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by dkorzh10** [sivannavis/samo#1]
Hello!

Could you please explain/add a code how to do inference only in countermeausre mode? :) E.g. 
```
def best_model_inference(path_to_audio_or_raw_wavefrom):
    ...
    return predicted_class
```
I'm not sure that I do inference correctly on my own, not just running default testing of eval set, because I got confused in the code and enrollments. 

Thank you in advance

**Comment by yzyouzhang** [comment]
It depends on your inference mode. If you have enrollment, we will calculate a speaker attractor from that, and calculate a cosine similarity. If you do not have enrollment, we will use the speaker attractors of training speakers, and the max cosine similarity will be used as the score.
Please refer to our [paper](https://arxiv.org/abs/2211.02718) for more details.

**Comment by adityatb** [comment]
Hi @yzyouzhang! Thanks for such a nice paper and sharing such meticulous results!

I'm still a bit confused about the inference part though - It seems as though the paper as well as the code are implementing an inner-product and not cosine-similarity. I'm not sure if I've missed something - Could you confirm if the code in this repo isn't using cosine-similarity but that's what I indeed should be using? Or should I indeed be using the dot-product as the code currently implements it?

**Comment by yzyouzhang** [comment]
> 

Thank you for your acknowledgment! 
You are right that we are using dot product to implement cosine similarity. Since we normalized the vectors before the calculation, I believe they are equivalent.

**Comment by sivannavis** [comment]
Thanks for the question! Please open a new issue if you have further questions.
